export const types = {
  FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE', 
  FETCH_PROJECTS_EMPTY:   'FETCH_PROJECTS_EMPTY', 
  CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
  FETCH_PROJECT_SUCCESS:  'FETCH_PROJECT_SUCCESS',
  FETCH_PROJECT_FAILURE:  'FETCH_PROJECT_FAILURE',
  SET_SHOULD_REDIRECT:    'SET_SHOULD_REDIRECT'
}
