export const types = {
  FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
  CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS'
}
